//translation table used to create item types
export const typeTable = {
  "G": "adventuring gear",
  "TG": "trade good",
  "FD": "food & drink",
  "TAH": "tack & harness",
  "AT": "artisan's tools",
  "GS": "gaming set",
  "T": "tool",
  "INS": "musical instrument",
  "MNT": "mount",
  "AIR": "vehicle (air)",
  "VEH": "vehicle (land)",
  "SHP": "vehicle (water)",
  "$": "treasure",
  "M": "melee weapon",
  "R": "ranged weapon",
  "A": "ammunition",
  "LA": "light armor",
  "MA": "medium armor",
  "HA": "heavy armor",
  "RG": "ring",
  "RD": "rod",
  "WD": "wand",
  "S": "shield",
  "SCF": "spellcasting focus",
  "AEN": "armor enchantment",
  "WEN": "weapon enchantment",
  "P": "consumable",
  "SC": "consumable",
  "EXP": "consumable",
  "WON": "wonderous item",
  "OTH": "other"
}